on:
  workflow_dispatch:
  schedule:
    - cron: '00 21 * * *'

jobs:
  create_event_summaries:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Install mpop
        run: sudo apt-get install -y mpop
      - name: Configure mpop
        env:
          MPOPRC: ${{ secrets.MPOPRC }}
        run: |
          envsubst <<< $(echo $MPOPRC | base64 --decode) > ~/.mpoprc
          chmod 600 ~/.mpoprc
      - name: Run mpop
        run: |
          mpop
          test -f ${{ github.workspace }}/data/raw/mbox
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV
      - name: Read message box
        run: python3 src/read_mbox.py ${{ github.workspace }}/data/raw/mbox
      - name: Filter messages
        run: python3 src/filter_messages.py ${{ github.workspace }}/data/raw/mbox.jsonl
      - name: Moderate messages
        run: python3 src/moderate_messages.py ${{ github.workspace }}/data/raw/mbox_filtered.jsonl
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - name: Create event summaries
        run: python3 src/prompt_messages.py ${{ github.workspace }}/data/raw/mbox_filtered_moderated.jsonl
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - name: Update calendar
        run: python3 src/update_calendar.py ${{ github.workspace }}/data/calendars
      - uses: stefanzweifel/git-auto-commit-action@v4
